### ISSUE TITLE
0x... as hexadecimal notation of an integer is not supported for IntRange

### ISSUE THREAD

**Issue by brickpool** [tobyink/p5-moox-press#1]
The use of `IntRange[0, 0xffff]` generates the following error ...
_0xffff is not a known type constraint at c:/Perl64/site/lib/MooX/Press.pm line 1969._

```
package Test
{
  use Zydeco;

  class WideChar
  {
    has WideChar ( type => Int, is => "rw" );

    method UnicodeChar(IntRange[0, 0xffff] $value?)
    {
      ...
```

Maybe this is the more correct place
https://github.com/tobyink/p5-type-tiny/issues
because `IntRange` is provided by [Types::Common::Numeric](https://github.com/tobyink/p5-type-tiny/blob/d051aba5ada2294e04f28fa94165e16d638fab7c/lib/Types/Common/Numeric.pm#L127)

**Comment by tobyink** [comment]
What happens if you upgrade to Type::Parser 1.012002?

**Comment by brickpool** [comment]
```
package Test
{
  use Zydeco;

  class WideChar
  {
    has WideChar ( type => Int, is => "rw" );

    method UnicodeChar(IntRange[0, 0xffff] $value?)
    {
      ...
    }

    method AsciiChar(IntRange[-0x80, 0xff] $value?)
    {
      ...
```
`IntRange[0, 0xffff]` works, but `IntRange[-0x80, 0xff]` fails with the following message

_Illegal hexadecimal digit '-' ignored at c:/Perl64/site/lib/Type/Parser.pm line 125._

**Comment by tobyink** [comment]
Type::Tiny 1.12.3 should fix...
https://metacpan.org/release/TOBYINK/Type-Tiny-1.012003

**Comment by brickpool** [comment]
Now `IntRange[-0x80, 0xff]` works as expected. 
Thank you for the update and thank you for your great work in general !
