### ISSUE TITLE
Test fails with Sub::HandlesVia 0.033

### ISSUE THREAD

**Issue by andk** [tobyink/p5-moox-press#2]
Sample fail report: http://www.cpantesters.org/cpan/report/19c14c94-1559-11ed-abb5-cd5a556f59f2

**Comment by andk** [comment]
FWIW: still true for Sub::HandlesVia 0.034 according to http://www.cpantesters.org/cpan/report/c5c6c8b4-1687-11ed-ae8c-9c48911e929d

**Comment by tobyink** [comment]
Thanks. I've just released Sub::HandlesVia 0.035 which should fix things.
